import type { IndustryGroupKey } from "./industryGroups";
import type { IndustryKey } from "./industries";
import type { SubIndustryKey } from "./subIndustries";

type IndustryTree = {
  [G in IndustryGroupKey]: Partial<Record<IndustryKey, SubIndustryKey[]>>;
};

export const INDUSTRY_TREE: IndustryTree = {
  FINANCIAL: {
    BANKS: ["PUBLIC_SECTOR_BANK", "PRIVATE_SECTOR_BANK", "OTHER_BANK"],
    NBFC: ["NBFC", "MICROFINANCE", "HOUSING_FINANCE"],
    ASSET_MGMT: ["AMC", "INVESTMENT_COMPANY"],
    FINANCIAL_SERVICES: ["FINANCIAL_INSTITUTION", "FINANCIAL_PRODUCTS_DISTRIBUTOR", "OTHER_FINANCIAL_SERVICES"],
  },
  INSURANCE: {
    INSURANCE: ["LIFE_INSURANCE", "GENERAL_INSURANCE"],
    INSURANCE_DISTRIBUTORS: ["INSURANCE_DISTRIBUTORS"],
  },
  METALS: {
    IRON: ["IRON_AND_STEEL", "IRON_AND_STEEL_PRODUCTS", "PIG_IRON", "SPONGE_IRON"],
    ALUMINIUM: ["ALUMINIUM", "ALUMINIUM_COPPER_ZINC_PRODUCTS"],
    COPPER: ["COPPER"],
    ZINC: ["ZINC"],
    PRECIOUS_METALS: ["PRECIOUS_METALS"],
    OTHER_METALS: ["DIVERSIFIED_METALS", "FERRO_SILICA_MANGANESE", "TRADING_METALS", "TRADING_MINERALS"],
  },
  ENERGY: {
    POWER: ["POWER_GENERATION", "POWER_DISTRIBUTION", "POWER_TRANSMISSION", "POWER_TRADING", "INTEGRATED_POWER_UTILITIES", "MULTI_UTILITIES"],
    OIL_AND_GAS: ["REFINERIES_AND_MARKETING", "OIL_EXPLORATION", "OIL_STORAGE", "OIL_EQUIPMENT", "OFFSHORE_SUPPORT", "GAS_TRANSMISSION", "LPG_CNG_PNG_LNG", "TRADING_GAS"],
    COAL: ["COAL"],
  },
  CHEMICALS: {
    SPECIALTY_CHEMICALS: ["SPECIALTY_CHEMICALS", "DYES_AND_PIGMENTS", "PRINTING_INKS", "CARBON_BLACK"],
    AGRI_CHEMICALS: ["PESTICIDES", "FERTILIZERS"],
    COMMODITY_CHEMICALS: ["COMMODITY_CHEMICALS", "PETROCHEMICALS", "INDUSTRIAL_GASES"],
    INDUSTRIAL_CHEMICALS: ["INDUSTRIAL_MINERALS", "ELECTRODES_REFRACTORIES", "LUBRICANTS"],
    TRADING_CHEMICALS: ["TRADING_CHEMICALS"],
  },
  INDUSTRIAL: {
    ELECTRICAL: ["HEAVY_ELECTRICAL", "OTHER_ELECTRICAL"],
    MACHINERY: ["COMPRESSORS_PUMPS"],
    COMPONENTS: ["ABRASIVES_BEARINGS", "CASTINGS_FORGINGS"],
    INDUSTRIAL_PRODUCTS: ["INDUSTRIAL_PRODUCTS", "OTHER_INDUSTRIAL_PRODUCTS", "GLASS_INDUSTRIAL"],
  },
  AUTO: {
    OEM: ["COMMERCIAL_VEHICLES", "TRACTORS", "PASSENGER_CARS", "TWO_THREE_WHEELERS", "CONSTRUCTION_VEHICLES"],
    ANCILLARY: ["TYRES_RUBBER", "AUTO_COMPONENTS", "TRADING_AUTO"],
    DEALER: ["AUTO_DEALER", "DEALERS_CV"],
  },
  INFRASTRUCTURE: {
    CIVIL_CONSTRUCTION: ["CIVIL_CONSTRUCTION"],
    ROAD: ["LOGISTICS", "ROAD_TRANSPORT", "TRANSPORT_SERVICES", "ROAD_ASSETS"],
    RAIL: ["RAILWAY_WAGONS"],
    SEA: ["PORT_SERVICES", "SHIP_BUILDING", "SHIPPING", "DREDGING"],
    AIR: ["AIRLINE", "AIRPORT_SERVICES"],
  },
  CONSTRUCTION: {
    MATERIALS: ["CEMENT", "PAINTS", "CERAMICS", "CABLES_ELECTRICALS", "SANITARY_WARE", "PLYWOOD_LAMINATES", "GLASS_CONSUMER", "OTHER_CONSTRUCTION_MATERIALS"],
    REAL_ESTATE: ["RESIDENTIAL_COMMERCIAL", "REAL_ESTATE_SERVICES", "REITS"],
  },
  CONSUMER: {
    STAPLES: ["CIGARETTES_TOBACCO", "DIVERSIFIED_FMCG", "HOUSEHOLD_PRODUCTS", "PACKAGED_FOODS", "PERSONAL_CARE"],
    RETAIL: ["DIVERSIFIED_RETAIL", "E_RETAIL", "FOOTWEAR", "GARMENTS_APPARELS", "INTERNET_CATALOGUE_RETAIL", "PHARMACY_RETAIL", "PLASTIC_PRODUCTS_CONSUMER", "SPECIALITY_RETAIL"],
    DURABLES: ["CONSUMER_ELECTRONICS", "HOUSEHOLD_APPLIANCES", "HOUSEWARE"],
    DISCRETIONARY: ["AMUSEMENT_PARKS", "GEMS_JEWELLERY", "HOTELS_RESORTS", "LEISURE_PRODUCTS", "RESTAURANTS", "TOUR_TRAVEL", "WELLNESS"],
  },
  FB: {
    BEVERAGES: ["BREWERIES_DISTILLERIES", "TEA_COFFEE", "OTHER_BEVERAGES"],
    FB_STAPLES: ["SUGAR", "EDIBLE_OIL", "DAIRY_PRODUCTS"],
    PROTEIN: ["MEAT_POULTRY", "SEAFOOD"],
    OTHER_FB: ["OTHER_FOOD_PRODUCTS", "ANIMAL_FEED"],
  },
  TEXTILE: {
    TEXTILE_ALL: ["OTHER_TEXTILE", "TRADING_TEXTILE"],
  },
  CRAFT_TYPE: {
    CRAFT_OTHER: ["FOREST_PRODUCTS", "FURNITURE", "GRANITES_MARBLES", "JUTE_PRODUCTS", "LEATHER_PRODUCTS", "PRINTING_PUBLICATION", "STATIONARY"],
  },
  MEDIA: {
    ENTERTAINMENT: ["FILM_PRODUCTION", "TV_BROADCASTING", "DIGITAL_ENTERTAINMENT", "MEDIA_ENTERTAINMENT"],
    ADVERTISING: ["ADVERTISING_AGENCIES"],
    DIGITAL_MEDIA: ["WEB_MEDIA", "ELECTRONIC_MEDIA"],
    PRINT_MEDIA: ["PRINT_MEDIA"],
  },
  HEALTHCARE: {
    PHARMA: ["PHARMACEUTICALS"],
    HEALTHCARE_SERVICES: ["HOSPITAL", "HEALTHCARE_SERVICE_PROVIDER"],
    EQUIPMENT: ["MEDICAL_EQUIPMENT", "HEALTHCARE_RESEARCH"],
  },
  TECH: {
    IT_SERVICES: ["SOFTWARE_CONSULTING", "IT_ENABLED_SERVICES", "SOFTWARE_PRODUCTS", "E_LEARNING", "FINTECH"],
    TELECOM: ["TELECOM_CELLULAR", "OTHER_TELECOM", "TELECOM_INFRASTRUCTURE", "TELECOM_EQUIPMENT"],
    HARDWARE: ["COMPUTERS_HARDWARE"],
    BIOTECH: ["BIOTECHNOLOGY"],
  },
  DEFENSE: {
    DEFENSE_OTHER: ["AEROSPACE_DEFENSE"],
  },
};
