import { IndustryGroupKey } from "./industryGroups";
import { IndustryKey } from "./industries";
import { SubIndustryKey } from "./subIndustries";

export enum StockKey {
  RELIANCE = "RELIANCE",
  CCLPRODUCTS = "CCLPRODUCTS",
  MTARTECH = "MTARTECH",
  AZAD = "AZAD",
  SONACOMS = "SONACOMS",
  BLUESTARCO = "BLUESTARCO",
  VOLTAS = "VOLTAS",
  HAVELLS = "HAVELLS",
  EPACK = "EPACK",
  AMBER = "AMBER",
  PGEL = "PGEL",
  SYMPHONY = "SYMPHONY",
  VBL = "VBL",
  SKYGOLD = "SKYGOLD",
  KAYNES = "KAYNES",
  TIINDIA = "TIINDIA",
  ZAGGLE = "ZAGGLE",
  KEC = "KEC",
  TECHNOELECTRIC = "TECHNOELECTRIC",
  ANANTRAJ = "ANANTRAJ",
  HAL = "HAL",
  VISHALMEGA = "VISHALMEGA",
  EIEL = "EIEL",
  ASIANPAINT = "ASIANPAINT",
  TCS = "TCS",
  TARIL = "TARIL",
  JIOFINANCE = "JIOFINANCE",
}

export interface StockInfo {
  name: string;
  screenerUrl: string;
  subIndustry: SubIndustryKey;
  industry: IndustryKey;
  industryGroup: IndustryGroupKey;
}

export const STOCKS: Record<StockKey, StockInfo> = {
  [StockKey.RELIANCE]: {
    name: "Reliance Industries",
    screenerUrl: "https://www.screener.in/company/RELIANCE/",
    subIndustry: SubIndustryKey.REFINERIES_AND_MARKETING,
    industry: IndustryKey.OIL_AND_GAS,
    industryGroup: IndustryGroupKey.ENERGY,
  },
  [StockKey.CCLPRODUCTS]: {
    name: "CCL Products",
    screenerUrl: "https://www.screener.in/company/CCL/",
    subIndustry: SubIndustryKey.TEA_COFFEE,
    industry: IndustryKey.BEVERAGES,
    industryGroup: IndustryGroupKey.FB,
  },
  [StockKey.MTARTECH]: {
    name: "MTAR Technologies",
    screenerUrl: "https://www.screener.in/company/MTARTECH/",
    subIndustry: SubIndustryKey.AEROSPACE_DEFENSE,
    industry: IndustryKey.DEFENSE_OTHER,
    industryGroup: IndustryGroupKey.DEFENSE,
  },
  [StockKey.AZAD]: {
    name: "Azad Engineering",
    screenerUrl: "https://www.screener.in/company/AZAD/",
    subIndustry: SubIndustryKey.HEAVY_ELECTRICAL,
    industry: IndustryKey.ELECTRICAL,
    industryGroup: IndustryGroupKey.INDUSTRIAL,
  },
  [StockKey.SONACOMS]: {
    name: "Sona BLW",
    screenerUrl: "https://www.screener.in/company/SONACOMS/",
    subIndustry: SubIndustryKey.AUTO_COMPONENTS,
    industry: IndustryKey.ANCILLARY,
    industryGroup: IndustryGroupKey.AUTO,
  },
  [StockKey.BLUESTARCO]: {
    name: "Blue Star",
    screenerUrl: "https://www.screener.in/company/BLUESTARCO/",
    subIndustry: SubIndustryKey.HOUSEHOLD_APPLIANCES,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.VOLTAS]: {
    name: "Voltas",
    screenerUrl: "https://www.screener.in/company/VOLTAS/",
    subIndustry: SubIndustryKey.HOUSEHOLD_APPLIANCES,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.HAVELLS]: {
    name: "Havells",
    screenerUrl: "https://www.screener.in/company/HAVELLS/",
    subIndustry: SubIndustryKey.CONSUMER_ELECTRONICS,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.EPACK]: {
    name: "Epack Durable",
    screenerUrl: "https://www.screener.in/company/EPACK/",
    subIndustry: SubIndustryKey.HOUSEHOLD_APPLIANCES,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.AMBER]: {
    name: "Amber Enterprises",
    screenerUrl: "https://www.screener.in/company/AMBER/",
    subIndustry: SubIndustryKey.HOUSEHOLD_APPLIANCES,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.PGEL]: {
    name: "PG Electroplast",
    screenerUrl: "https://www.screener.in/company/PGEL/",
    subIndustry: SubIndustryKey.CONSUMER_ELECTRONICS,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.SYMPHONY]: {
    name: "Symphony",
    screenerUrl: "https://www.screener.in/company/SYMPHONY/",
    subIndustry: SubIndustryKey.HOUSEHOLD_APPLIANCES,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.VBL]: {
    name: "Varun Beverages",
    screenerUrl: "https://www.screener.in/company/VBL/",
    subIndustry: SubIndustryKey.OTHER_BEVERAGES,
    industry: IndustryKey.BEVERAGES,
    industryGroup: IndustryGroupKey.FB,
  },
  [StockKey.SKYGOLD]: {
    name: "Sky Gold",
    screenerUrl: "https://www.screener.in/company/SKYGOLD/",
    subIndustry: SubIndustryKey.GEMS_JEWELLERY,
    industry: IndustryKey.DISCRETIONARY,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.KAYNES]: {
    name: "Kaynes Technology",
    screenerUrl: "https://www.screener.in/company/KAYNES/",
    subIndustry: SubIndustryKey.CONSUMER_ELECTRONICS,
    industry: IndustryKey.DURABLES,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.TIINDIA]: {
    name: "Tube Investments of India",
    screenerUrl: "https://www.screener.in/company/TIINDIA/",
    subIndustry: SubIndustryKey.AUTO_COMPONENTS,
    industry: IndustryKey.ANCILLARY,
    industryGroup: IndustryGroupKey.AUTO,
  },
  [StockKey.ZAGGLE]: {
    name: "Zaggle Prepaid",
    screenerUrl: "https://www.screener.in/company/ZAGGLE/",
    subIndustry: SubIndustryKey.FINTECH,
    industry: IndustryKey.IT_SERVICES,
    industryGroup: IndustryGroupKey.TECH,
  },
  [StockKey.KEC]: {
    name: "KEC International",
    screenerUrl: "https://www.screener.in/company/KEC/",
    subIndustry: SubIndustryKey.CIVIL_CONSTRUCTION,
    industry: IndustryKey.CIVIL_CONSTRUCTION,
    industryGroup: IndustryGroupKey.INFRASTRUCTURE,
  },
  [StockKey.TECHNOELECTRIC]: {
    name: "Techno Electric",
    screenerUrl: "https://www.screener.in/company/TECHNOE/",
    subIndustry: SubIndustryKey.CIVIL_CONSTRUCTION,
    industry: IndustryKey.CIVIL_CONSTRUCTION,
    industryGroup: IndustryGroupKey.INFRASTRUCTURE,
  },
  [StockKey.ANANTRAJ]: {
    name: "Anant Raj",
    screenerUrl: "https://www.screener.in/company/ANANTRAJ/",
    subIndustry: SubIndustryKey.RESIDENTIAL_COMMERCIAL,
    industry: IndustryKey.REAL_ESTATE,
    industryGroup: IndustryGroupKey.CONSTRUCTION,
  },
  [StockKey.HAL]: {
    name: "Hindustan Aeronautics",
    screenerUrl: "https://www.screener.in/company/HAL/",
    subIndustry: SubIndustryKey.AEROSPACE_DEFENSE,
    industry: IndustryKey.DEFENSE_OTHER,
    industryGroup: IndustryGroupKey.DEFENSE,
  },
  [StockKey.VISHALMEGA]: {
    name: "Vishal Mega Mart",
    screenerUrl: "https://www.screener.in/company/VMM/",
    subIndustry: SubIndustryKey.DIVERSIFIED_RETAIL,
    industry: IndustryKey.RETAIL,
    industryGroup: IndustryGroupKey.CONSUMER,
  },
  [StockKey.EIEL]: {
    name: "Enviro Infra Engineers",
    screenerUrl: "https://www.screener.in/company/EIEL/",
    subIndustry: SubIndustryKey.CIVIL_CONSTRUCTION,
    industry: IndustryKey.CIVIL_CONSTRUCTION,
    industryGroup: IndustryGroupKey.INFRASTRUCTURE,
  },
  [StockKey.ASIANPAINT]: {
    name: "Asian Paints",
    screenerUrl: "https://www.screener.in/company/ASIANPAINT/",
    subIndustry: SubIndustryKey.PAINTS,
    industry: IndustryKey.MATERIALS,
    industryGroup: IndustryGroupKey.CONSTRUCTION,
  },
  [StockKey.TCS]: {
    name: "Tata Consultancy Services",
    screenerUrl: "https://www.screener.in/company/TCS/",
    subIndustry: SubIndustryKey.SOFTWARE_CONSULTING,
    industry: IndustryKey.IT_SERVICES,
    industryGroup: IndustryGroupKey.TECH,
  },
  [StockKey.TARIL]: {
    name: "Taril",
    screenerUrl: "https://www.screener.in/company/TARIL/",
    subIndustry: SubIndustryKey.OTHER_INDUSTRIAL_PRODUCTS,
    industry: IndustryKey.INDUSTRIAL_PRODUCTS,
    industryGroup: IndustryGroupKey.INDUSTRIAL,
  },
  [StockKey.JIOFINANCE]: {
    name: "Jio Financial Services",
    screenerUrl: "https://www.screener.in/company/JIOFIN/",
    subIndustry: SubIndustryKey.NBFC,
    industry: IndustryKey.NBFC,
    industryGroup: IndustryGroupKey.FINANCIAL,
  },
};
