export enum SubIndustryKey {
  // FINANCIAL > Banks
  PUBLIC_SECTOR_BANK = "PUBLIC_SECTOR_BANK",
  PRIVATE_SECTOR_BANK = "PRIVATE_SECTOR_BANK",
  OTHER_BANK = "OTHER_BANK",
  // FINANCIAL > NBFC
  NBFC = "NBFC",
  MICROFINANCE = "MICROFINANCE",
  HOUSING_FINANCE = "HOUSING_FINANCE",
  // FINANCIAL > Asset Mgmt
  AMC = "AMC",
  INVESTMENT_COMPANY = "INVESTMENT_COMPANY",
  // FINANCIAL > Services
  FINANCIAL_INSTITUTION = "FINANCIAL_INSTITUTION",
  FINANCIAL_PRODUCTS_DISTRIBUTOR = "FINANCIAL_PRODUCTS_DISTRIBUTOR",
  OTHER_FINANCIAL_SERVICES = "OTHER_FINANCIAL_SERVICES",
  // INSURANCE
  LIFE_INSURANCE = "LIFE_INSURANCE",
  GENERAL_INSURANCE = "GENERAL_INSURANCE",
  INSURANCE_DISTRIBUTORS = "INSURANCE_DISTRIBUTORS",
  // METALS
  IRON_AND_STEEL = "IRON_AND_STEEL",
  IRON_AND_STEEL_PRODUCTS = "IRON_AND_STEEL_PRODUCTS",
  PIG_IRON = "PIG_IRON",
  SPONGE_IRON = "SPONGE_IRON",
  ALUMINIUM = "ALUMINIUM",
  ALUMINIUM_COPPER_ZINC_PRODUCTS = "ALUMINIUM_COPPER_ZINC_PRODUCTS",
  COPPER = "COPPER",
  ZINC = "ZINC",
  PRECIOUS_METALS = "PRECIOUS_METALS",
  DIVERSIFIED_METALS = "DIVERSIFIED_METALS",
  FERRO_SILICA_MANGANESE = "FERRO_SILICA_MANGANESE",
  TRADING_METALS = "TRADING_METALS",
  TRADING_MINERALS = "TRADING_MINERALS",
  // ENERGY
  POWER_GENERATION = "POWER_GENERATION",
  POWER_DISTRIBUTION = "POWER_DISTRIBUTION",
  POWER_TRANSMISSION = "POWER_TRANSMISSION",
  POWER_TRADING = "POWER_TRADING",
  INTEGRATED_POWER_UTILITIES = "INTEGRATED_POWER_UTILITIES",
  MULTI_UTILITIES = "MULTI_UTILITIES",
  REFINERIES_AND_MARKETING = "REFINERIES_AND_MARKETING",
  OIL_EXPLORATION = "OIL_EXPLORATION",
  OIL_STORAGE = "OIL_STORAGE",
  OIL_EQUIPMENT = "OIL_EQUIPMENT",
  OFFSHORE_SUPPORT = "OFFSHORE_SUPPORT",
  GAS_TRANSMISSION = "GAS_TRANSMISSION",
  LPG_CNG_PNG_LNG = "LPG_CNG_PNG_LNG",
  TRADING_GAS = "TRADING_GAS",
  COAL = "COAL",
  // CHEMICALS
  SPECIALTY_CHEMICALS = "SPECIALTY_CHEMICALS",
  DYES_AND_PIGMENTS = "DYES_AND_PIGMENTS",
  PRINTING_INKS = "PRINTING_INKS",
  CARBON_BLACK = "CARBON_BLACK",
  PESTICIDES = "PESTICIDES",
  FERTILIZERS = "FERTILIZERS",
  COMMODITY_CHEMICALS = "COMMODITY_CHEMICALS",
  PETROCHEMICALS = "PETROCHEMICALS",
  INDUSTRIAL_GASES = "INDUSTRIAL_GASES",
  INDUSTRIAL_MINERALS = "INDUSTRIAL_MINERALS",
  ELECTRODES_REFRACTORIES = "ELECTRODES_REFRACTORIES",
  LUBRICANTS = "LUBRICANTS",
  TRADING_CHEMICALS = "TRADING_CHEMICALS",
  // INDUSTRIAL
  HEAVY_ELECTRICAL = "HEAVY_ELECTRICAL",
  OTHER_ELECTRICAL = "OTHER_ELECTRICAL",
  COMPRESSORS_PUMPS = "COMPRESSORS_PUMPS",
  ABRASIVES_BEARINGS = "ABRASIVES_BEARINGS",
  CASTINGS_FORGINGS = "CASTINGS_FORGINGS",
  INDUSTRIAL_PRODUCTS = "INDUSTRIAL_PRODUCTS",
  OTHER_INDUSTRIAL_PRODUCTS = "OTHER_INDUSTRIAL_PRODUCTS",
  GLASS_INDUSTRIAL = "GLASS_INDUSTRIAL",
  // AUTO
  COMMERCIAL_VEHICLES = "COMMERCIAL_VEHICLES",
  TRACTORS = "TRACTORS",
  PASSENGER_CARS = "PASSENGER_CARS",
  TWO_THREE_WHEELERS = "TWO_THREE_WHEELERS",
  CONSTRUCTION_VEHICLES = "CONSTRUCTION_VEHICLES",
  TYRES_RUBBER = "TYRES_RUBBER",
  AUTO_COMPONENTS = "AUTO_COMPONENTS",
  TRADING_AUTO = "TRADING_AUTO",
  AUTO_DEALER = "AUTO_DEALER",
  DEALERS_CV = "DEALERS_CV",
  // INFRASTRUCTURE
  CIVIL_CONSTRUCTION = "CIVIL_CONSTRUCTION",
  LOGISTICS = "LOGISTICS",
  ROAD_TRANSPORT = "ROAD_TRANSPORT",
  TRANSPORT_SERVICES = "TRANSPORT_SERVICES",
  ROAD_ASSETS = "ROAD_ASSETS",
  RAILWAY_WAGONS = "RAILWAY_WAGONS",
  PORT_SERVICES = "PORT_SERVICES",
  SHIP_BUILDING = "SHIP_BUILDING",
  SHIPPING = "SHIPPING",
  DREDGING = "DREDGING",
  AIRLINE = "AIRLINE",
  AIRPORT_SERVICES = "AIRPORT_SERVICES",
  // CONSTRUCTION
  CEMENT = "CEMENT",
  PAINTS = "PAINTS",
  CERAMICS = "CERAMICS",
  CABLES_ELECTRICALS = "CABLES_ELECTRICALS",
  SANITARY_WARE = "SANITARY_WARE",
  PLYWOOD_LAMINATES = "PLYWOOD_LAMINATES",
  GLASS_CONSUMER = "GLASS_CONSUMER",
  OTHER_CONSTRUCTION_MATERIALS = "OTHER_CONSTRUCTION_MATERIALS",
  RESIDENTIAL_COMMERCIAL = "RESIDENTIAL_COMMERCIAL",
  REAL_ESTATE_SERVICES = "REAL_ESTATE_SERVICES",
  REITS = "REITS",
  // CONSUMER
  CIGARETTES_TOBACCO = "CIGARETTES_TOBACCO",
  DIVERSIFIED_FMCG = "DIVERSIFIED_FMCG",
  HOUSEHOLD_PRODUCTS = "HOUSEHOLD_PRODUCTS",
  PACKAGED_FOODS = "PACKAGED_FOODS",
  PERSONAL_CARE = "PERSONAL_CARE",
  DIVERSIFIED_RETAIL = "DIVERSIFIED_RETAIL",
  E_RETAIL = "E_RETAIL",
  FOOTWEAR = "FOOTWEAR",
  GARMENTS_APPARELS = "GARMENTS_APPARELS",
  INTERNET_CATALOGUE_RETAIL = "INTERNET_CATALOGUE_RETAIL",
  PHARMACY_RETAIL = "PHARMACY_RETAIL",
  PLASTIC_PRODUCTS_CONSUMER = "PLASTIC_PRODUCTS_CONSUMER",
  SPECIALITY_RETAIL = "SPECIALITY_RETAIL",
  CONSUMER_ELECTRONICS = "CONSUMER_ELECTRONICS",
  HOUSEHOLD_APPLIANCES = "HOUSEHOLD_APPLIANCES",
  HOUSEWARE = "HOUSEWARE",
  AMUSEMENT_PARKS = "AMUSEMENT_PARKS",
  GEMS_JEWELLERY = "GEMS_JEWELLERY",
  HOTELS_RESORTS = "HOTELS_RESORTS",
  LEISURE_PRODUCTS = "LEISURE_PRODUCTS",
  RESTAURANTS = "RESTAURANTS",
  TOUR_TRAVEL = "TOUR_TRAVEL",
  WELLNESS = "WELLNESS",
  // F&B
  BREWERIES_DISTILLERIES = "BREWERIES_DISTILLERIES",
  TEA_COFFEE = "TEA_COFFEE",
  OTHER_BEVERAGES = "OTHER_BEVERAGES",
  SUGAR = "SUGAR",
  EDIBLE_OIL = "EDIBLE_OIL",
  DAIRY_PRODUCTS = "DAIRY_PRODUCTS",
  MEAT_POULTRY = "MEAT_POULTRY",
  SEAFOOD = "SEAFOOD",
  OTHER_FOOD_PRODUCTS = "OTHER_FOOD_PRODUCTS",
  ANIMAL_FEED = "ANIMAL_FEED",
  // TEXTILE
  OTHER_TEXTILE = "OTHER_TEXTILE",
  TRADING_TEXTILE = "TRADING_TEXTILE",
  // CRAFT TYPE
  FOREST_PRODUCTS = "FOREST_PRODUCTS",
  FURNITURE = "FURNITURE",
  GRANITES_MARBLES = "GRANITES_MARBLES",
  JUTE_PRODUCTS = "JUTE_PRODUCTS",
  LEATHER_PRODUCTS = "LEATHER_PRODUCTS",
  PRINTING_PUBLICATION = "PRINTING_PUBLICATION",
  STATIONARY = "STATIONARY",
  // MEDIA
  FILM_PRODUCTION = "FILM_PRODUCTION",
  TV_BROADCASTING = "TV_BROADCASTING",
  DIGITAL_ENTERTAINMENT = "DIGITAL_ENTERTAINMENT",
  MEDIA_ENTERTAINMENT = "MEDIA_ENTERTAINMENT",
  ADVERTISING_AGENCIES = "ADVERTISING_AGENCIES",
  WEB_MEDIA = "WEB_MEDIA",
  ELECTRONIC_MEDIA = "ELECTRONIC_MEDIA",
  PRINT_MEDIA = "PRINT_MEDIA",
  // HEALTHCARE
  PHARMACEUTICALS = "PHARMACEUTICALS",
  HOSPITAL = "HOSPITAL",
  HEALTHCARE_SERVICE_PROVIDER = "HEALTHCARE_SERVICE_PROVIDER",
  MEDICAL_EQUIPMENT = "MEDICAL_EQUIPMENT",
  HEALTHCARE_RESEARCH = "HEALTHCARE_RESEARCH",
  // TECH
  SOFTWARE_CONSULTING = "SOFTWARE_CONSULTING",
  IT_ENABLED_SERVICES = "IT_ENABLED_SERVICES",
  SOFTWARE_PRODUCTS = "SOFTWARE_PRODUCTS",
  E_LEARNING = "E_LEARNING",
  FINTECH = "FINTECH",
  TELECOM_CELLULAR = "TELECOM_CELLULAR",
  OTHER_TELECOM = "OTHER_TELECOM",
  TELECOM_INFRASTRUCTURE = "TELECOM_INFRASTRUCTURE",
  TELECOM_EQUIPMENT = "TELECOM_EQUIPMENT",
  COMPUTERS_HARDWARE = "COMPUTERS_HARDWARE",
  BIOTECHNOLOGY = "BIOTECHNOLOGY",
  // DEFENSE
  AEROSPACE_DEFENSE = "AEROSPACE_DEFENSE",
}

interface SubIndustryInfo {
  name: string;
}

export const SUB_INDUSTRIES: Record<SubIndustryKey, SubIndustryInfo> = {
  [SubIndustryKey.PUBLIC_SECTOR_BANK]: { name: "Public Sector Bank" },
  [SubIndustryKey.PRIVATE_SECTOR_BANK]: { name: "Private Sector Bank" },
  [SubIndustryKey.OTHER_BANK]: { name: "Other Bank" },
  [SubIndustryKey.NBFC]: { name: "Non Banking Financial Company (NBFC)" },
  [SubIndustryKey.MICROFINANCE]: { name: "Microfinance Institutions" },
  [SubIndustryKey.HOUSING_FINANCE]: { name: "Housing Finance Company" },
  [SubIndustryKey.AMC]: { name: "Asset Management Company" },
  [SubIndustryKey.INVESTMENT_COMPANY]: { name: "Investment Company" },
  [SubIndustryKey.FINANCIAL_INSTITUTION]: { name: "Financial Institution" },
  [SubIndustryKey.FINANCIAL_PRODUCTS_DISTRIBUTOR]: { name: "Financial Products Distributor" },
  [SubIndustryKey.OTHER_FINANCIAL_SERVICES]: { name: "Other Financial Services" },
  [SubIndustryKey.LIFE_INSURANCE]: { name: "Life Insurance" },
  [SubIndustryKey.GENERAL_INSURANCE]: { name: "General Insurance" },
  [SubIndustryKey.INSURANCE_DISTRIBUTORS]: { name: "Insurance Distributors" },
  [SubIndustryKey.IRON_AND_STEEL]: { name: "Iron & Steel" },
  [SubIndustryKey.IRON_AND_STEEL_PRODUCTS]: { name: "Iron & Steel Products" },
  [SubIndustryKey.PIG_IRON]: { name: "Pig Iron" },
  [SubIndustryKey.SPONGE_IRON]: { name: "Sponge Iron" },
  [SubIndustryKey.ALUMINIUM]: { name: "Aluminium" },
  [SubIndustryKey.ALUMINIUM_COPPER_ZINC_PRODUCTS]: { name: "Aluminium, Copper & Zinc Products" },
  [SubIndustryKey.COPPER]: { name: "Copper" },
  [SubIndustryKey.ZINC]: { name: "Zinc" },
  [SubIndustryKey.PRECIOUS_METALS]: { name: "Precious Metals" },
  [SubIndustryKey.DIVERSIFIED_METALS]: { name: "Diversified Metals" },
  [SubIndustryKey.FERRO_SILICA_MANGANESE]: { name: "Ferro & Silica Manganese" },
  [SubIndustryKey.TRADING_METALS]: { name: "Trading - Metals" },
  [SubIndustryKey.TRADING_MINERALS]: { name: "Trading - Minerals" },
  [SubIndustryKey.POWER_GENERATION]: { name: "Power Generation" },
  [SubIndustryKey.POWER_DISTRIBUTION]: { name: "Power Distribution" },
  [SubIndustryKey.POWER_TRANSMISSION]: { name: "Power - Transmission" },
  [SubIndustryKey.POWER_TRADING]: { name: "Power Trading" },
  [SubIndustryKey.INTEGRATED_POWER_UTILITIES]: { name: "Integrated Power Utilities" },
  [SubIndustryKey.MULTI_UTILITIES]: { name: "Multi Utilities" },
  [SubIndustryKey.REFINERIES_AND_MARKETING]: { name: "Refineries & Marketing" },
  [SubIndustryKey.OIL_EXPLORATION]: { name: "Oil Exploration & Production" },
  [SubIndustryKey.OIL_STORAGE]: { name: "Oil Storage & Transportation" },
  [SubIndustryKey.OIL_EQUIPMENT]: { name: "Oil Equipment & Services" },
  [SubIndustryKey.OFFSHORE_SUPPORT]: { name: "Offshore Support Solution Drilling" },
  [SubIndustryKey.GAS_TRANSMISSION]: { name: "Gas Transmission/Marketing" },
  [SubIndustryKey.LPG_CNG_PNG_LNG]: { name: "LPG/CNG/PNG/LNG Supplier" },
  [SubIndustryKey.TRADING_GAS]: { name: "Trading - Gas" },
  [SubIndustryKey.COAL]: { name: "Coal" },
  [SubIndustryKey.SPECIALTY_CHEMICALS]: { name: "Specialty Chemicals" },
  [SubIndustryKey.DYES_AND_PIGMENTS]: { name: "Dyes And Pigments" },
  [SubIndustryKey.PRINTING_INKS]: { name: "Printing Inks" },
  [SubIndustryKey.CARBON_BLACK]: { name: "Carbon Black" },
  [SubIndustryKey.PESTICIDES]: { name: "Pesticides & Agrochemicals" },
  [SubIndustryKey.FERTILIZERS]: { name: "Fertilizers" },
  [SubIndustryKey.COMMODITY_CHEMICALS]: { name: "Commodity Chemicals" },
  [SubIndustryKey.PETROCHEMICALS]: { name: "Petrochemicals" },
  [SubIndustryKey.INDUSTRIAL_GASES]: { name: "Industrial Gases" },
  [SubIndustryKey.INDUSTRIAL_MINERALS]: { name: "Industrial Minerals" },
  [SubIndustryKey.ELECTRODES_REFRACTORIES]: { name: "Electrodes & Refractories" },
  [SubIndustryKey.LUBRICANTS]: { name: "Lubricants" },
  [SubIndustryKey.TRADING_CHEMICALS]: { name: "Trading - Chemicals" },
  [SubIndustryKey.HEAVY_ELECTRICAL]: { name: "Heavy Electrical Equipment" },
  [SubIndustryKey.OTHER_ELECTRICAL]: { name: "Other Electrical Equipment" },
  [SubIndustryKey.COMPRESSORS_PUMPS]: { name: "Compressors, Pumps & Diesel Engines" },
  [SubIndustryKey.ABRASIVES_BEARINGS]: { name: "Abrasives & Bearings" },
  [SubIndustryKey.CASTINGS_FORGINGS]: { name: "Castings & Forgings" },
  [SubIndustryKey.INDUSTRIAL_PRODUCTS]: { name: "Industrial Products" },
  [SubIndustryKey.OTHER_INDUSTRIAL_PRODUCTS]: { name: "Other Industrial Products" },
  [SubIndustryKey.GLASS_INDUSTRIAL]: { name: "Glass - Industrial" },
  [SubIndustryKey.COMMERCIAL_VEHICLES]: { name: "Commercial Vehicles" },
  [SubIndustryKey.TRACTORS]: { name: "Tractors" },
  [SubIndustryKey.PASSENGER_CARS]: { name: "Passenger Cars & Utility Vehicles" },
  [SubIndustryKey.TWO_THREE_WHEELERS]: { name: "2/3 Wheelers" },
  [SubIndustryKey.CONSTRUCTION_VEHICLES]: { name: "Construction Vehicles" },
  [SubIndustryKey.TYRES_RUBBER]: { name: "Tyres & Rubber Products" },
  [SubIndustryKey.AUTO_COMPONENTS]: { name: "Auto Components & Equipments" },
  [SubIndustryKey.TRADING_AUTO]: { name: "Trading - Auto components" },
  [SubIndustryKey.AUTO_DEALER]: { name: "Auto Dealer" },
  [SubIndustryKey.DEALERS_CV]: { name: "Dealers-Commercial Vehicles, Tractors, Construction Vehicles" },
  [SubIndustryKey.CIVIL_CONSTRUCTION]: { name: "Civil Construction" },
  [SubIndustryKey.LOGISTICS]: { name: "Logistics Solution Provider" },
  [SubIndustryKey.ROAD_TRANSPORT]: { name: "Road Transport" },
  [SubIndustryKey.TRANSPORT_SERVICES]: { name: "Transport Related Services" },
  [SubIndustryKey.ROAD_ASSETS]: { name: "Road AssetsToll, Annuity, Hybrid-Annuity" },
  [SubIndustryKey.RAILWAY_WAGONS]: { name: "Railway Wagons" },
  [SubIndustryKey.PORT_SERVICES]: { name: "Port & Port services" },
  [SubIndustryKey.SHIP_BUILDING]: { name: "Ship Building & Allied Services" },
  [SubIndustryKey.SHIPPING]: { name: "Shipping" },
  [SubIndustryKey.DREDGING]: { name: "Dredging" },
  [SubIndustryKey.AIRLINE]: { name: "Airline" },
  [SubIndustryKey.AIRPORT_SERVICES]: { name: "Airport & Airport services" },
  [SubIndustryKey.CEMENT]: { name: "Cement & Cement Products" },
  [SubIndustryKey.PAINTS]: { name: "Paints" },
  [SubIndustryKey.CERAMICS]: { name: "Ceramics" },
  [SubIndustryKey.CABLES_ELECTRICALS]: { name: "Cables - Electricals" },
  [SubIndustryKey.SANITARY_WARE]: { name: "Sanitary Ware" },
  [SubIndustryKey.PLYWOOD_LAMINATES]: { name: "Plywood Boards/ Laminates" },
  [SubIndustryKey.GLASS_CONSUMER]: { name: "Glass - Consumer" },
  [SubIndustryKey.OTHER_CONSTRUCTION_MATERIALS]: { name: "Other Construction Materials" },
  [SubIndustryKey.RESIDENTIAL_COMMERCIAL]: { name: "Residential, Commercial Projects" },
  [SubIndustryKey.REAL_ESTATE_SERVICES]: { name: "Real Estate related services" },
  [SubIndustryKey.REITS]: { name: "Real Estate Investment Trusts (REITs)" },
  [SubIndustryKey.CIGARETTES_TOBACCO]: { name: "Cigarettes & Tobacco Products" },
  [SubIndustryKey.DIVERSIFIED_FMCG]: { name: "Diversified FMCG" },
  [SubIndustryKey.HOUSEHOLD_PRODUCTS]: { name: "Household Products" },
  [SubIndustryKey.PACKAGED_FOODS]: { name: "Packaged Foods" },
  [SubIndustryKey.PERSONAL_CARE]: { name: "Personal Care" },
  [SubIndustryKey.DIVERSIFIED_RETAIL]: { name: "Diversified Retail" },
  [SubIndustryKey.E_RETAIL]: { name: "E-Retail/ E-Commerce" },
  [SubIndustryKey.FOOTWEAR]: { name: "Footwear" },
  [SubIndustryKey.GARMENTS_APPARELS]: { name: "Garments & Apparels" },
  [SubIndustryKey.INTERNET_CATALOGUE_RETAIL]: { name: "Internet & Catalogue Retail" },
  [SubIndustryKey.PHARMACY_RETAIL]: { name: "Pharmacy Retail" },
  [SubIndustryKey.PLASTIC_PRODUCTS_CONSUMER]: { name: "Plastic Products - Consumer" },
  [SubIndustryKey.SPECIALITY_RETAIL]: { name: "Speciality Retail" },
  [SubIndustryKey.CONSUMER_ELECTRONICS]: { name: "Consumer Electronics" },
  [SubIndustryKey.HOUSEHOLD_APPLIANCES]: { name: "Household Appliances" },
  [SubIndustryKey.HOUSEWARE]: { name: "Houseware" },
  [SubIndustryKey.AMUSEMENT_PARKS]: { name: "Amusement Parks/ Other Recreation" },
  [SubIndustryKey.GEMS_JEWELLERY]: { name: "Gems, Jewellery And Watches" },
  [SubIndustryKey.HOTELS_RESORTS]: { name: "Hotels & Resorts" },
  [SubIndustryKey.LEISURE_PRODUCTS]: { name: "Leisure Products" },
  [SubIndustryKey.RESTAURANTS]: { name: "Restaurants" },
  [SubIndustryKey.TOUR_TRAVEL]: { name: "Tour, Travel Related Services" },
  [SubIndustryKey.WELLNESS]: { name: "Wellness" },
  [SubIndustryKey.BREWERIES_DISTILLERIES]: { name: "Breweries & Distilleries" },
  [SubIndustryKey.TEA_COFFEE]: { name: "Tea & Coffee" },
  [SubIndustryKey.OTHER_BEVERAGES]: { name: "Other Beverages" },
  [SubIndustryKey.SUGAR]: { name: "Sugar" },
  [SubIndustryKey.EDIBLE_OIL]: { name: "Edible Oil" },
  [SubIndustryKey.DAIRY_PRODUCTS]: { name: "Dairy Products" },
  [SubIndustryKey.MEAT_POULTRY]: { name: "Meat Products including Poultry" },
  [SubIndustryKey.SEAFOOD]: { name: "Seafood" },
  [SubIndustryKey.OTHER_FOOD_PRODUCTS]: { name: "Other Food Products" },
  [SubIndustryKey.ANIMAL_FEED]: { name: "Animal Feed" },
  [SubIndustryKey.OTHER_TEXTILE]: { name: "Other Textile Products" },
  [SubIndustryKey.TRADING_TEXTILE]: { name: "Trading - Textile Products" },
  [SubIndustryKey.FOREST_PRODUCTS]: { name: "Forest Products" },
  [SubIndustryKey.FURNITURE]: { name: "Furniture, Home Furnishing" },
  [SubIndustryKey.GRANITES_MARBLES]: { name: "Granites & Marbles" },
  [SubIndustryKey.JUTE_PRODUCTS]: { name: "Jute & Jute Products" },
  [SubIndustryKey.LEATHER_PRODUCTS]: { name: "Leather And Leather Products" },
  [SubIndustryKey.PRINTING_PUBLICATION]: { name: "Printing & Publication" },
  [SubIndustryKey.STATIONARY]: { name: "Stationary" },
  [SubIndustryKey.FILM_PRODUCTION]: { name: "Film Production, Distribution & Exhibition" },
  [SubIndustryKey.TV_BROADCASTING]: { name: "TV Broadcasting & Software Production" },
  [SubIndustryKey.DIGITAL_ENTERTAINMENT]: { name: "Digital Entertainment" },
  [SubIndustryKey.MEDIA_ENTERTAINMENT]: { name: "Media & Entertainment" },
  [SubIndustryKey.ADVERTISING_AGENCIES]: { name: "Advertising & Media Agencies" },
  [SubIndustryKey.WEB_MEDIA]: { name: "Web based media and service" },
  [SubIndustryKey.ELECTRONIC_MEDIA]: { name: "Electronic Media" },
  [SubIndustryKey.PRINT_MEDIA]: { name: "Print Media" },
  [SubIndustryKey.PHARMACEUTICALS]: { name: "Pharmaceuticals" },
  [SubIndustryKey.HOSPITAL]: { name: "Hospital" },
  [SubIndustryKey.HEALTHCARE_SERVICE_PROVIDER]: { name: "Healthcare Service Provider" },
  [SubIndustryKey.MEDICAL_EQUIPMENT]: { name: "Medical Equipment & Supplies" },
  [SubIndustryKey.HEALTHCARE_RESEARCH]: { name: "Healthcare Research, Analytics & Technology" },
  [SubIndustryKey.SOFTWARE_CONSULTING]: { name: "Computers - Software & Consulting" },
  [SubIndustryKey.IT_ENABLED_SERVICES]: { name: "IT Enabled Services" },
  [SubIndustryKey.SOFTWARE_PRODUCTS]: { name: "Software Products" },
  [SubIndustryKey.E_LEARNING]: { name: "E-Learning" },
  [SubIndustryKey.FINTECH]: { name: "Financial Technology (Fintech)" },
  [SubIndustryKey.TELECOM_CELLULAR]: { name: "Telecom - Cellular & Fixed line services" },
  [SubIndustryKey.OTHER_TELECOM]: { name: "Other Telecom Services" },
  [SubIndustryKey.TELECOM_INFRASTRUCTURE]: { name: "Telecom - Infrastructure" },
  [SubIndustryKey.TELECOM_EQUIPMENT]: { name: "Telecom - Equipment & Accessories" },
  [SubIndustryKey.COMPUTERS_HARDWARE]: { name: "Computers Hardware & Equipments" },
  [SubIndustryKey.BIOTECHNOLOGY]: { name: "Biotechnology" },
  [SubIndustryKey.AEROSPACE_DEFENSE]: { name: "Aerospace & Defense" },
};
